# -*- coding: utf-8 -*-
"""Forward_Interface_Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bnRVh2x2brqQMKI1kN5R5xYELRwMJmSC

# Bates Grain Interface
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import savgol_filter
import joblib
from tensorflow.keras.models import load_model

# ==========================================
# 1. Loading Model and Scalers
# ==========================================
print("Loading Bates Model and Scalers...")
try:
    # تحميل النموذج (بدون compile لتجنب أخطاء دوال الـ Loss)
    my_model = load_model('Bates_model.keras', compile=False)

    # تحميل الـ 4 Scalers
    my_s_X = joblib.load('scaler_X.pkl')
    my_s_yt = joblib.load('scaler_thrust.pkl')
    my_s_yp = joblib.load('scaler_pressure.pkl')
    my_s_ys = joblib.load('scaler_scalars.pkl')

    print("✅ Model and Scalers loaded successfully!\n")
except Exception as e:
    print(f" Error loading files: {e}")
    raise e

# ==========================================
# 2. Prediction Function
# ==========================================
def get_user_input_and_predict_bates(model, s_X, s_yt, s_yp, s_ys):
    print("\n" + "="*50)
    print("--- Enter the dimensions of the Bates Grain for prediction ---")
    print("="*50)
    try:
        # 1. استلام المدخلات
        l_val = float(input("Length: "))
        d_val = float(input("Diameter: "))
        c_d_val = float(input("Core_Diameter: "))
        t_d_val = float(input("Throat_Diameter: "))
        e_d_val = float(input("Exit_Diameter: "))

        # Input arrangement (بنفس ترتيب التدريب)
        user_inputs = np.array([[l_val, d_val, c_d_val, t_d_val, e_d_val]])
        user_inputs_scaled = s_X.transform(user_inputs)

        # 2. Prediction
        preds = model.predict(user_inputs_scaled, verbose=0)

        # 3. فك تشفير النتائج (Inverse Transform)
        thrust_pred = s_yt.inverse_transform(preds[0])
        pressure_pred = s_yp.inverse_transform(preds[1])
        scalars_pred = s_ys.inverse_transform(preds[2])

        # Preparing the timeline
        burn_time = scalars_pred[0][2]
        time_steps = np.linspace(0, burn_time, 100)

        # Calculating the Impulse mathematically
        calculated_impulse = np.trapz(thrust_pred[0], time_steps)

        print("\n" + "-"*40)
        print("--- Predicted Performance Results ---")
        print("-"*40)
        print(f"ISP: {scalars_pred[0][0]:.2f} s")
        print(f"Total Impulse (Calculated): {calculated_impulse:.2f} N.s")
        print(f"Burn Time: {burn_time:.2f} s")
        print(f"Max Thrust: {scalars_pred[0][3]:.2f} N")
        print("-"*40 + "\n")

        # تنعيم المنحنيات باستخدام savgol_filter
        smoothed_pressure = savgol_filter(pressure_pred[0], window_length=15, polyorder=3)
        smoothed_thrust = savgol_filter(thrust_pred[0], window_length=15, polyorder=3)

        # رسم النتائج
        plt.figure(figsize=(15, 5))

        #   (Thrust Plot)
        plt.subplot(1, 2, 1)
        plt.plot(time_steps, smoothed_thrust, color='red', linewidth=2)
        plt.title('Predicted Thrust Curve')
        plt.xlabel('Time (s)')
        plt.ylabel('Thrust (N)')
        plt.grid(True, alpha=0.3)

        #   (Pressure Plot)
        plt.subplot(1, 2, 2)
        plt.plot(time_steps, smoothed_pressure, color='blue', linewidth=2)
        plt.title('Predicted Pressure Curve')
        plt.xlabel('Time (s)')
        plt.ylabel('Pressure (MPa)')
        plt.grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

    except ValueError:
        print("\n[Error]: Please enter valid numeric values.")
    except Exception as e:
        print(f"\n[Error]: An unexpected error occurred: {e}")

# ==========================================
# 3. Execution
# ==========================================
if __name__ == "__main__":
    get_user_input_and_predict_bates(my_model, my_s_X, my_s_yt, my_s_yp, my_s_ys)

"""# D Grain Interface"""

import pickle
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model

def get_user_input_and_predict_grain_d():
    # ─── Load Model and Scalers inside the function to prevent NameError ───
    try:
        model = load_model('/kaggle/input/datasets/mahmoudabdelrazek11/d-tast/grain_d_model.keras', compile=False)

        with open('/kaggle/input/datasets/mahmoudabdelrazek11/d-tast/grain_d_scalers.pkl', 'rb') as f:
            scalers_dict = pickle.load(f)

        s_X = scalers_dict['s_X']
        s_yt = scalers_dict['s_yt']
        s_yp = scalers_dict['s_yp']
        s_ys = scalers_dict['s_ys']
    except FileNotFoundError:
        print("\n[Error]: Model or Scaler files not found in the current directory!")
        print("Please ensure 'grain_d_model.keras' and 'grain_d_scalers.pkl' are present.")
        return
    except Exception as e:
        print(f"\n[Error]: An error occurred while loading files: {e}")
        return

    # ─── User Interface and Inference ───
    print("\n" + "="*50)
    print("--- Enter the dimensions of Grain D for prediction ---")
    print("="*50)
    try:
        l_val = float(input("Length: "))
        d_val = float(input("Diameter: "))
        so_val = float(input("Slot Offset: "))
        t_d_val = float(input("Throat Diameter: "))
        e_d_val = float(input("Exit Diameter: "))

        # Format inputs to match the original training column order
        user_inputs = np.array([[l_val, d_val, so_val, t_d_val, e_d_val]])
        user_inputs_scaled = s_X.transform(user_inputs)

        # Model Prediction
        preds = model.predict(user_inputs_scaled, verbose=0)

        # Inverse Transform to original scales
        thrust_pred = s_yt.inverse_transform(preds[0])
        pressure_pred = s_yp.inverse_transform(preds[1])
        scalars_pred = s_ys.inverse_transform(preds[2])

        # Extract scalar values
        isp = scalars_pred[0][0]
        predicted_impulse = scalars_pred[0][1]
        burn_time = scalars_pred[0][2]
        max_thrust = scalars_pred[0][3]

        # Prepare the timeline
        time_steps = np.linspace(0, burn_time, 100)
        calculated_impulse = np.trapezoid(thrust_pred[0], time_steps)

        print("\n" + "-"*40)
        print("--- Predicted Performance Results (Grain D) ---")
        print("-"*40)
        print(f"ISP: {isp:.2f} s")
        print(f"Total Impulse (Model): {predicted_impulse:.2f} N.s")
        print(f"Total Impulse (Calculated Area): {calculated_impulse:.2f} N.s")
        print(f"Burn Time: {burn_time:.2f} s")
        print(f"Max Thrust: {max_thrust:.2f} N")
        print("-"*40 + "\n")

        # Plotting curves (without smoothing filters to preserve raw physics)
        plt.figure(figsize=(15, 5))

        # Thrust Plot
        plt.subplot(1, 2, 1)
        plt.plot(time_steps, thrust_pred[0], color='red', linewidth=2)
        plt.title('Predicted Thrust Curve (Grain D)')
        plt.xlabel('Time (s)')
        plt.ylabel('Thrust (N)')
        plt.grid(True, alpha=0.3)

        # Pressure Plot
        plt.subplot(1, 2, 2)
        plt.plot(time_steps, pressure_pred[0], color='blue', linewidth=2)
        plt.title('Predicted Pressure Curve (Grain D)')
        plt.xlabel('Time (s)')
        plt.ylabel('Pressure (MPa)')
        plt.grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

    except ValueError:
        print("\n[Error]: Please enter valid numeric values.")
    except Exception as e:
        print(f"\n[Error]: An unexpected error occurred: {e}")

# Run the function
get_user_input_and_predict_grain_d()

"""# Moon Grain Interface"""

import joblib
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from scipy.signal import savgol_filter

# ===================================================================
# Moon Grain - Performance Predictor (Forward Model Engine)
# ===================================================================
def get_user_input_and_predict_moon():
    print('\n' + '='*55)
    print('   Moon Grain - Performance Predictor (ReLU Edition)')
    print('='*55)

    # ─── 1. Load Model and Scalers Safely Inside to Prevent NameErrors ───
    try:
        # compile=False bypasses missing custom training loss/metrics functions
        moon_forward = load_model('/kaggle/input/datasets/mahmoudabdelrazek11/moon-test/Moon_Forward_Model.keras', compile=False)

        # Load the saved configuration elements
        s_X  = joblib.load('/kaggle/input/datasets/mahmoudabdelrazek11/moon-test/moon_fwd_scaler_X.pkl')
        s_ys = joblib.load('/kaggle/input/datasets/mahmoudabdelrazek11/moon-test/moon_fwd_scaler_scalars.pkl')

        # Extract physical normalization dictionary max constraints
        max_vals = joblib.load('/kaggle/input/datasets/mahmoudabdelrazek11/moon-test/moon_fwd_max_values.pkl')
        yt_max = max_vals['yt_max']
        yp_max = max_vals['yp_max']

    except FileNotFoundError as e:
        print(f"\n[Error]: Missing required deployment asset file. Please check paths.\nDetails: {e}")
        return
    except Exception as e:
        print(f"\n[Error]: An unexpected runtime loading error occurred: {e}")
        return

    # ─── 2. Handle Dimensional User Inputs ───
    try:
        l_val  = float(input('Length (cm):               '))
        od_val = float(input('Outer Diameter (cm):       '))
        id_val = float(input('Inner Diameter/Core (cm):  '))
        co_val = float(input('Core Offset (cm):          '))
        td_val = float(input('Throat Diameter (cm):      '))
        ed_val = float(input('Exit Diameter (cm):        '))

        # Prepare structural input matrix boundary shape
        user_inputs        = np.array([[l_val, od_val, id_val, co_val, td_val, ed_val]])
        user_inputs_scaled = s_X.transform(user_inputs)

        # Execute Forward Network Call
        preds = moon_forward.predict(user_inputs_scaled, verbose=0)

        # ─── 3. Rescale Output Performance Horizons ───
        # De-normalize profile shapes via absolute max weights
        thrust_pred   = preds[0][0] * yt_max
        pressure_pred = preds[1][0] * yp_max

        # De-normalize constant metrics via Scikit-Learn standard scalar
        scalars_pred  = s_ys.inverse_transform(preds[2])[0]
        isp           = max(scalars_pred[0], 1e-9)
        burn_time     = max(scalars_pred[2], 1e-9)

        time_steps = np.linspace(0, burn_time, 100)

        # ─── 4. Preprocessing and Tail Conditioning ───
        # Apply Savitzky-Golay filtering safely clipped below zero
        smoothed_thrust   = np.clip(savgol_filter(thrust_pred, window_length=7, polyorder=2), 0, None)
        smoothed_pressure = np.clip(savgol_filter(pressure_pred, window_length=7, polyorder=2), 0, None)

        # Close out tail anomalies past structural regression limits
        peak_idx = np.argmax(smoothed_thrust)
        tail     = smoothed_thrust[peak_idx:]
        cutoff   = np.argmax(tail < 0.02 * smoothed_thrust.max())
        if cutoff > 0:
            smoothed_thrust[peak_idx + cutoff:] = 0
            smoothed_pressure[peak_idx + cutoff:] = 0

        # Calculate integration area under the finalized conditioned curves
        calculated_impulse = np.trapezoid(smoothed_thrust, time_steps)
        final_max_thrust = np.max(smoothed_thrust)

        # ─── 5. Print Results Table ───
        print('\n' + '-'*45)
        print('   Predicted Performance (Moon Grain)')
        print('-'*45)
        print(f'   ISP                   : {isp:.2f} s')
        print(f'   Burn Time             : {burn_time:.2f} s')
        print(f'   Total Impulse         : {calculated_impulse:.2f} N.s')
        print(f'   Max Thrust            : {final_max_thrust:.2f} N')
        print('-'*45)

        # ─── 6. Visualization Profiles Plot ───
        fig, axes = plt.subplots(1, 2, figsize=(15, 5))

        # Subplot 1: Rescaled Thrust Curve
        axes[0].plot(time_steps, smoothed_thrust, color='red', linewidth=2)
        axes[0].set_title('Predicted Thrust Curve')
        axes[0].set_xlabel('Time (s)')
        axes[0].set_ylabel('Thrust (N)')
        axes[0].grid(True, alpha=0.3)

        # Subplot 2: Rescaled Chamber Pressure Curve
        axes[1].plot(time_steps, smoothed_pressure, color='blue', linewidth=2)
        axes[1].set_title('Predicted Pressure Curve')
        axes[1].set_xlabel('Time (s)')
        axes[1].set_ylabel('Pressure (MPa)')
        axes[1].grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

    except ValueError:
        print('\n[Error]: Please enter valid numeric values.')
    except Exception as e:
        print(f'\n[Error]: {e}')

# Run the function
get_user_input_and_predict_moon()

"""# Road and Tube Grain Interface"""

import os
import joblib
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import get_file

# --- Define your model and scaler paths/URLs here ---
# If a path starts with 'http' or 'https', the file will be downloaded.
# Otherwise, it will be treated as a local file path.
model_path = 'rocket_motor_golden_rod_improved.keras'
scaler_X_path = 'scaler_X.pkl'
scaler_t_path = 'scaler_t.pkl'
scaler_p_path = 'scaler_p.pkl'
scaler_Ys_path = 'scaler_Ys.pkl'

def get_local_path(resource_path):
    if resource_path.startswith('http://') or resource_path.startswith('https://'):
        print(f"Downloading {resource_path}...")
        try:
            local_path = get_file(os.path.basename(resource_path), resource_path)
            print(f"Downloaded to {local_path}")
            return local_path
        except Exception as e:
            print(f"❌ Failed to download from {resource_path}: {e}")
            return None
    return resource_path

# Get local paths (download if URLs are provided)
model_path = get_local_path(model_path)
scaler_X_path = get_local_path(scaler_X_path)
scaler_t_path = get_local_path(scaler_t_path)
scaler_p_path = get_local_path(scaler_p_path)
scaler_Ys_path = get_local_path(scaler_Ys_path)

# --- Load Model and Scalers ---
loaded_model = None
loaded_scaler_X = None
loaded_scaler_t = None
loaded_scaler_p = None
loaded_scaler_Ys = None

try:
    # Load Model
    if model_path and os.path.exists(model_path):
        loaded_model = load_model(model_path)
        print(f"✅ Model loaded successfully from {model_path}")
    else:
        print(f"❌ Model file not found or could not be downloaded at {model_path}")

    # Load Scaler_X
    if scaler_X_path and os.path.exists(scaler_X_path):
        loaded_scaler_X = joblib.load(scaler_X_path)
        print(f"✅ scaler_X loaded successfully from {scaler_X_path}")
    else:
        print(f"❌ scaler_X file not found or could not be downloaded at {scaler_X_path}")

    # Load Scaler_t
    if scaler_t_path and os.path.exists(scaler_t_path):
        loaded_scaler_t = joblib.load(scaler_t_path)
        print(f"✅ scaler_t loaded successfully from {scaler_t_path}")
    else:
        print(f"❌ scaler_t file not found or could not be downloaded at {scaler_t_path}")

    # Load Scaler_p
    if scaler_p_path and os.path.exists(scaler_p_path):
        loaded_scaler_p = joblib.load(scaler_p_path)
        print(f"✅ scaler_p loaded successfully from {scaler_p_path}")
    else:
        print(f"❌ scaler_p file not found or could not be downloaded at {scaler_p_path}")

    # Load Scaler_Ys
    if scaler_Ys_path and os.path.exists(scaler_Ys_path):
        loaded_scaler_Ys = joblib.load(scaler_Ys_path)
        print(f"✅ scaler_Ys loaded successfully from {scaler_Ys_path}")
    else:
        print(f"❌ scaler_Ys file not found or could not be downloaded at {scaler_Ys_path}")

    if all([loaded_model, loaded_scaler_X, loaded_scaler_t, loaded_scaler_p, loaded_scaler_Ys]):
        print("\nAll files loaded. You can now use the 'loaded_model', 'loaded_scaler_X', 'loaded_scaler_t', 'loaded_scaler_p', and 'loaded_scaler_Ys' objects.")
    else:
        print("\nSome files could not be loaded. Please check the paths/URLs and try again.")

except Exception as e:
    print(f"An error occurred during loading: {e}")


import numpy as np

print("\nPlease enter the dimensions for your rocket 1.3motor (numerical values expected):\n")

# Get user inputs for the 7 dimensions
try:
    length = float(input("Enter Length (e.g., 130.0): "))
    diameter = float(input("Enter Diameter (e.g., 20.0): "))
    core_diameter = float(input("Enter Core Diameter (e.g., 4.0): "))
    rod_diameter = float(input("Enter Rod Diameter (e.g., 1.0): "))
    support_diameter = float(input("Enter Support Diameter (e.g., 0.0): "))
    throat_diameter = float(input("Enter Throat Diameter (e.g., 2.9): "))
    exit_diameter = float(input("Enter Exit Diameter (e.g., 4.35): "))

    custom_design_inputs = [
        length, diameter, core_diameter, rod_diameter,
        support_diameter, throat_diameter, exit_diameter
    ]

    print("\nSimulating motor with your design...")
    # Call the simulate_new_motor function with the global loaded model and scalers
    simulate_new_motor(
        loaded_model,
        loaded_scaler_X,
        loaded_scaler_Ys,
        loaded_scaler_t,
        loaded_scaler_p,
        custom_design_inputs
    )
    print("\n✅ Simulation completed successfully!")

except ValueError:
    print("❌ Invalid input. Please ensure all dimensions are entered as numbers.")
except NameError:
    print("❌ Error: 'loaded_model' or scalers not found. Please ensure the model and scalers are loaded first.")
except Exception as e:
    print(f"❌ An unexpected error occurred: {e}")

"""# Star Grain Interface"""

import os
import joblib
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
from scipy.signal import savgol_filter

# ===================================================================
# Star Grain Motor — AI Performance Prediction (Forward Engine)
# ===================================================================
def predict_star_grain():
    """
    Inputs (all in cm):
      Length, Outer Diameter, Number of Points,
      Point Length, Point Base Width, Throat Diameter, Exit Diameter
    Outputs:
      Thrust profile (N) + Pressure profile (MPa)
      ISP (s), Total Impulse (Ns), Burn Time (s), Max Thrust (N)
    """
    print('\n' + '='*55)
    print('   Star Grain Motor — AI Performance Prediction')
    print('='*55)

    # ─── 1. Load Model and Scalers Safely Inside to Prevent NameErrors ───
    try:
        # compile=False bypasses custom loss function compilation flags during inference
        model = load_model('/kaggle/input/datasets/mahmoudabdelrazek11/star-test/Star_model.keras', compile=False)

        # Load the saved Scikit-Learn scalers
        s_X  = joblib.load('/kaggle/input/datasets/mahmoudabdelrazek11/star-test/scaler_X.pkl')
        s_yt = joblib.load('/kaggle/input/datasets/mahmoudabdelrazek11/star-test/scaler_thrust.pkl')
        s_yp = joblib.load('/kaggle/input/datasets/mahmoudabdelrazek11/star-test/scaler_pressure.pkl')
        s_ys = joblib.load('/kaggle/input/datasets/mahmoudabdelrazek11/star-test/scaler_scalars.pkl')

    except FileNotFoundError as e:
        print(f"\n[Error]: Missing required deployment asset files. Please check paths.\nDetails: {e}")
        return
    except Exception as e:
        print(f"\n[Error]: An unexpected model loading error occurred: {e}")
        return

    # ─── 2. Handle Dimensional User Inputs ───
    try:
        length    = float(input('Length (cm):              '))
        diameter  = float(input('Outer Diameter (cm):      '))
        n_points  = float(input('Number of Points (3/5/7/9): '))
        pt_length = float(input('Point Length (cm):        '))
        pt_width  = float(input('Point Base Width (cm):    '))
        throat    = float(input('Throat Diameter (cm):     '))
        exit_d    = float(input('Exit Diameter (cm):       '))

        # Prepare structural input matrix boundary shape
        user_in = np.array([[length, diameter, n_points, pt_length, pt_width, throat, exit_d]])
        user_sc = s_X.transform(user_in)

        # Execute Forward Network Predictions
        preds = model.predict(user_sc, verbose=0)

        # ─── 3. Rescale Output Performance Profiles ───
        thrust_pred   = s_yt.inverse_transform(preds[0])[0]
        pressure_pred = s_yp.inverse_transform(preds[1])[0]
        scalars_pred  = s_ys.inverse_transform(preds[2])[0]

        burn_time  = max(scalars_pred[2], 1e-9)
        time_steps = np.linspace(0, burn_time, 100)

        # Calculate integration area under the curve (Handles both trapz and trapezoid)
        if hasattr(np, 'trapezoid'):
            impulse = np.trapezoid(thrust_pred, time_steps)
        else:
            impulse = np.trapz(thrust_pred, time_steps)

        # Preprocessing: Savitzky-Golay Smoothing for Plotting
        thrust_smooth   = np.clip(savgol_filter(thrust_pred,   window_length=15, polyorder=3), 0, None)
        pressure_smooth = np.clip(savgol_filter(pressure_pred, window_length=15, polyorder=3), 0, None)

        # ─── 4. Print Performance Metrics Summary ───
        print('\n' + '-'*45)
        print('   Predicted Performance Results')
        print('-'*45)
        print(f'   ISP:              {scalars_pred[0]:.2f} s')
        print(f'   Total Impulse:    {impulse:.2f} Ns')
        print(f'   Burn Time:        {burn_time:.2f} s')
        print(f'   Max Thrust:       {scalars_pred[3]:.2f} N')
        print('-'*45 + '\n')

        # ─── 5. Visualization Profiles Plot ───
        plt.figure(figsize=(15, 5))

        # Subplot 1: Thrust Profile Curve
        plt.subplot(1, 2, 1)
        plt.plot(time_steps, thrust_smooth, color='red', linewidth=2)
        plt.title('Predicted Thrust Profile')
        plt.xlabel('Time (s)')
        plt.ylabel('Thrust (N)')
        plt.grid(True, alpha=0.3)

        # Subplot 2: Chamber Pressure Profile Curve
        plt.subplot(1, 2, 2)
        plt.plot(time_steps, pressure_smooth, color='blue', linewidth=2)
        plt.title('Predicted Chamber Pressure')
        plt.xlabel('Time (s)')
        plt.ylabel('Pressure (MPa)')
        plt.grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

    except ValueError:
        print('\n[Error]: Please enter valid numeric values.')
    except Exception as e:
        print(f'\n[Error]: An unexpected prediction error occurred: {e}')

# Execute the engine
predict_star_grain()

"""# X Grain Interface"""

import numpy as np
import pickle
from tensorflow.keras.models import load_model

def predict_rocket_motor(input_values):
    # 1. Load the scalers and constants file
    with open("D:\\project\\X-core\\x-grain forward\\scalers_and_constants (1).pkl", 'rb') as f:
        scalers_and_constants = pickle.load(f)

    scaler_X = scalers_and_constants['scaler_X']
    scaler_ys = scalers_and_constants['scaler_ys']

    # 2. Load the trained Keras Model
    model = load_model("D:\\project\\X-core\\x-grain forward\\rocket_motor_model (1).h5")

    # 3. Prepare the input data
    input_data = np.array([input_values])

    # 4. Scale the inputs
    scaled_input = scaler_X.transform(input_data)

    # 5. Generate predictions (verbose=0 to hide the progress bar)
    predictions = model.predict(scaled_input, verbose=0)

    # Extract only the scalar predictions (the 3rd output)
    scaled_scalars = predictions[2]

    # 6. Inverse transform the outputs
    final_prediction = scaler_ys.inverse_transform(scaled_scalars)

    return final_prediction[0]

# ==========================================
# Input data and execution block
# ==========================================
if __name__ == "__main__":
    print("==================================================")
    print("   Rocket Motor Performance Prediction Program    ")
    print("==================================================")
    print("Please enter the 6 required geometry dimensions:\n")

    # Define the exact names of the input features based on the model
    input_labels = [
        "Length (L) in mm",
        "Diameter (D) in mm",
        "Slot Length (S_L) in mm",
        "Slot Width (S_W) in mm",
        "Throat Diameter (T_D) in mm",
        "Exit Diameter (E_D) in mm"
    ]

    try:
        # Receive the 6 inputs interactively from the user
        my_inputs = []
        for label in input_labels:
            val = float(input(f"Enter {label}: "))
            my_inputs.append(val)

        print("\nCalculating predictions, please wait...")
        results = predict_rocket_motor(my_inputs)

        # The correct order of the output metrics
        output_labels = [
            "ISP (s)",
            "Total Impulse (Ns)",
            "Burn Time (s)",
            "Max Thrust (N)",
            "Peak Pressure (MPa)"
        ]

        # Print the results neatly
        print("\n==================================================")
        print("           Final Predicted Results                ")
        print("==================================================")
        for label, value in zip(output_labels, results):
            print(f"{label:<22} : {value:.4f}")
        print("==================================================")

    except ValueError:
        print("\nError: Please enter valid numeric values only!")
    except Exception as e:
        print(f"\nAn error occurred during execution: {e}")

"""# C Grain Interface"""

import pandas as pd
import numpy as np
import joblib
import tensorflow as tf
import os
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d
from scipy.integrate import trapezoid

MODEL_PATH = r"C_Forward_Model.keras"

SCALAR_SCALER_PATH = r"c_fwd_scaler_scalars.pkl"

Value_SCALER_PATH = r"c_fwd_max_values.pkl"
SCALAR_X_PATH  = r"c_fwd_scaler_X.pkl"

s_X = joblib.load(SCALAR_X_PATH)
s_ys = joblib.load(SCALAR_SCALER_PATH)
c_forward = tf.keras.models.load_model(MODEL_PATH)
def get_user_input_and_predict_c():
    print('\n' + '='*55)
    print('   Co Grain - Performance Predictor (ReLU Edition)')
    print('='*55)
    try:
        l_val  = float(input('Length (cm):               '))
        od_val = float(input('Diameter (cm):             '))
        id_val = float(input('Slot_Width (cm):           '))
        co_val = float(input('Slot_Offest (cm):          '))
        td_val = float(input('Throat Diameter (cm):      '))
        ed_val = float(input('Exit Diameter (cm):        '))

        user_inputs        = np.array([[l_val, od_val, id_val, co_val, td_val, ed_val]])
        user_inputs_scaled = s_X.transform(user_inputs)

        preds = c_forward.predict(user_inputs_scaled, verbose=0)

        max_vals = joblib.load(Value_SCALER_PATH)
        yt_max = max_vals['yt_max']
        yp_max = max_vals['yp_max']

        # استخراج المنحنيات
        thrust_pred   = preds[0][0] * yt_max
        pressure_pred = preds[1][0] * yp_max

        # استخراج القيم الثابتة
        scalars_pred  = s_ys.inverse_transform(preds[2])[0]

        isp       = max(scalars_pred[0], 1e-9)
        burn_time = max(scalars_pred[1], 1e-9)

        time_steps = np.linspace(0, burn_time, 100)

        raw_impulse = np.trapezoid(thrust_pred, time_steps)

        print(f'Raw Curve Impulse : {raw_impulse:.2f} N.s')

        # تنعيم خفيف للمنحنى بدون التأثير على القمة
        #smoothed_thrust   = np.clip(savgol_filter(thrust_pred, window_length=7, polyorder=2), 0, None)
        #smoothed_pressure = np.clip(savgol_filter(pressure_pred, window_length=7, polyorder=2), 0, None)
        smoothed_thrust   = thrust_pred.copy()
        smoothed_pressure = pressure_pred.copy()

        # إغلاق ذيل المنحنى
        # peak_idx = np.argmax(smoothed_thrust)
        # tail     = smoothed_thrust[peak_idx:]
        # cutoff   = np.argmax(tail < 0.02 * smoothed_thrust.max())
        # if cutoff > 0:
        #     smoothed_thrust[peak_idx + cutoff:] = 0
        #     smoothed_pressure[peak_idx + cutoff:] = 0

        # حساب المساحة من المنحنى النهائي
        #predicted_impulse = scalars_pred[1]
        final_max_thrust = np.max(thrust_pred)
        calculated_impulse = np.trapezoid(thrust_pred, time_steps)

        print('\n' + '-'*45)
        print('   Predicted Performance (Co Grain)')
        print('-'*45)
        print(f'  ISP                    : {isp:.2f} s')
        print(f'  Burn Time              : {burn_time:.2f} s')

        print(f'  Max Thrust             : {final_max_thrust:.2f} N')
        print(f'  Total Impulse          : {calculated_impulse:.2f} N.s')
        print('-'*45)

        fig, axes = plt.subplots(1, 2, figsize=(15, 5))

        axes[0].plot(time_steps, smoothed_thrust, color='red', linewidth=2)
        axes[0].set_title('Predicted Thrust Curve')
        axes[0].set_xlabel('Time (s)'); axes[0].set_ylabel('Thrust (N)')
        axes[0].grid(True, alpha=0.3)

        axes[1].plot(time_steps, smoothed_pressure, color='blue', linewidth=2)
        axes[1].set_title('Predicted Pressure Curve')
        axes[1].set_xlabel('Time (s)'); axes[1].set_ylabel('Pressure (MPa)')
        axes[1].grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

    except ValueError:
        print('\n[Error]: Please enter valid numeric values.')
    except Exception as e:
        print(f'\n[Error]: {e}')

get_user_input_and_predict_c()

"""# Conical Grain Interface"""

import pandas as pd
import numpy as np
import joblib
import tensorflow as tf
import os
from scipy.signal import savgol_filter
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d
from scipy.integrate import trapezoid

MODEL_PATH = r"Conical_Forward_Model.keras"

SCALAR_SCALER_PATH = r"conical_fwd_scaler_scalars.pkl"

Value_SCALER_PATH = r"conical_fwd_max_values.pkl"

SCALAR_X_PATH  = r"conical_fwd_scaler_X.pkl"

s_X = joblib.load(SCALAR_X_PATH)
s_ys = joblib.load(SCALAR_SCALER_PATH)
conical_forward = tf.keras.models.load_model(MODEL_PATH)

# ===================================================================
# Prediction Function for Conical Forward Model (Clean Curve)
# ===================================================================
def get_user_input_and_predict_conical():
    print('\n' + '='*55)
    print('   Moon Grain - Performance Predictor (ReLU Edition)')
    print('='*55)
    try:
        l_val  = float(input('Length (cm):               '))
        od_val = float(input('Diameter (cm):       '))
        id_val = float(input('Forward_Core_Diameter (cm):  '))
        co_val = float(input('Aft_Core_Diameter (cm):          '))
        td_val = float(input('Throat Diameter (cm):      '))
        ed_val = float(input('Exit Diameter (cm):        '))

        user_inputs        = np.array([[l_val, od_val, id_val, co_val, td_val, ed_val]])
        user_inputs_scaled = s_X.transform(user_inputs)

        preds = conical_forward.predict(user_inputs_scaled, verbose=0)

        max_vals = joblib.load(Value_SCALER_PATH)
        yt_max = max_vals['yt_max']
        yp_max = max_vals['yp_max']

        # استخراج المنحنيات
        thrust_pred   = preds[0][0] * yt_max
        pressure_pred = preds[1][0] * yp_max

        # استخراج القيم الثابتة
        scalars_pred  = s_ys.inverse_transform(preds[2])[0]
        isp           = max(scalars_pred[0], 1e-9)
        burn_time     = max(scalars_pred[2], 1e-9)
        max_thrust_sc = max(scalars_pred[3], 1e-9)

        time_steps = np.linspace(0, burn_time, 100)

        # تنعيم خفيف للمنحنى بدون التأثير على القمة
        smoothed_thrust   = np.clip(savgol_filter(thrust_pred, window_length=7, polyorder=2), 0, None)
        smoothed_pressure = np.clip(savgol_filter(pressure_pred, window_length=7, polyorder=2), 0, None)

        # إغلاق ذيل المنحنى
        peak_idx = np.argmax(smoothed_thrust)
        tail     = smoothed_thrust[peak_idx:]
        cutoff   = np.argmax(tail < 0.02 * smoothed_thrust.max())
        if cutoff > 0:
            smoothed_thrust[peak_idx + cutoff:] = 0
            smoothed_pressure[peak_idx + cutoff:] = 0

        # حساب المساحة من المنحنى النهائي
        calculated_impulse = np.trapezoid(smoothed_thrust, time_steps)
        final_max_thrust = np.max(smoothed_thrust)

        print('\n' + '-'*45)
        print('   Predicted Performance (Conical Grain)')
        print('-'*45)
        print(f'  ISP                   : {isp:.2f} s')
        print(f'  Burn Time             : {burn_time:.2f} s')
        print(f'  Total Impulse         : {calculated_impulse:.2f} N.s')
        print(f'  Max Thrust            : {final_max_thrust:.2f} N')
        print('-'*45)

        fig, axes = plt.subplots(1, 2, figsize=(15, 5))

        axes[0].plot(time_steps, smoothed_thrust, color='red', linewidth=2)
        axes[0].set_title('Predicted Thrust Curve')
        axes[0].set_xlabel('Time (s)'); axes[0].set_ylabel('Thrust (N)')
        axes[0].grid(True, alpha=0.3)

        axes[1].plot(time_steps, smoothed_pressure, color='blue', linewidth=2)
        axes[1].set_title('Predicted Pressure Curve')
        axes[1].set_xlabel('Time (s)'); axes[1].set_ylabel('Pressure (MPa)')
        axes[1].grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

    except ValueError:
        print('\n[Error]: Please enter valid numeric values.')
    except Exception as e:
        print(f'\n[Error]: {e}')

get_user_input_and_predict_conical()

"""# Finocyl Grain Interface"""

import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
import os


from scipy.interpolate import interp1d
from scipy.signal import savgol_filter

import tensorflow as tf

MODEL_PATH = r"finocyl_forward_v3_final.keras"

params_SCALER_PATH = r"fin_v3_norm_params.pkl"

ys_SCALER_PATH = r"fin_v3_scaler_ys.pkl"

SCALAR_X_PATH  = r"fin_v3_scaler_X.pkl"

s_X = joblib.load(SCALAR_X_PATH)
s_ys = joblib.load(ys_SCALER_PATH)
finocyl_forward = tf.keras.models.load_model(MODEL_PATH, compile=False)
N_POINTS     = 200

# ===================================================================
# Prediction Function V3
# ===================================================================
def predict_finocyl_v3(
    diameter, length, core_diameter,
    num_fins, fin_length, fin_width,
    throat_diameter, exit_diameter,
    plot=True, smooth_output=True
):
    """
    التنبؤ بأداء محرك Finocyl — V3

    Parameters
    ----------
    diameter, length, core_diameter : أبعاد الجسم والقلب (cm)
    num_fins, fin_length, fin_width : عدد الزعانف وأبعادها
    throat_diameter, exit_diameter  : أبعاد الفوهة (cm)
    smooth_output : bool — تنعيم إضافي خفيف على الـ output
                   (للعرض فقط، لا يؤثر على الـ scalars)
    """
    norm_params = joblib.load(params_SCALER_PATH)
    T_MAX = norm_params['thrust_max']
    P_MAX = norm_params['pres_max']

    inp_arr    = np.array([[diameter, length, core_diameter, num_fins,
                             fin_length, fin_width, throat_diameter, exit_diameter]],
                           dtype=np.float32)
    inp_scaled = s_X.transform(inp_arr)

    preds = finocyl_forward.predict(inp_scaled, verbose=0)

    thrust_curve   = np.clip(preds[0][0] * T_MAX, 0, None)
    pressure_curve = np.clip(preds[1][0] * P_MAX, 0, None)

    # Optional light post-smoothing للعرض (لا يغير القيم المتوقعة)
    if smooth_output:
        thrust_curve   = np.clip(savgol_filter(thrust_curve,   window_length=11, polyorder=3), 0, None)
        pressure_curve = np.clip(savgol_filter(pressure_curve, window_length=11, polyorder=3), 0, None)

    sc_log    = s_ys.inverse_transform(preds[2])
    sc_vals   = np.expm1(sc_log)[0]

    burn_time     = max(float(sc_vals[0]), 0.1)
    isp           = max(float(sc_vals[1]), 1.0)
    total_impulse = max(float(sc_vals[2]), 1.0)
    max_thrust_sc = max(float(sc_vals[3]), 1.0)
    peak_pres     = max(float(sc_vals[4]), 0.01)

    time_steps    = np.linspace(0, burn_time, N_POINTS)
    calc_impulse  = float(np.trapz(thrust_curve, time_steps))

    print('\n' + '=' * 58)
    print('   Finocyl Forward V3 — Prediction Results')
    print('=' * 58)
    print(f'  Burn Time          : {burn_time:.3f} s')
    print(f'  ISP                : {isp:.2f} s')
    print(f'  Total Impulse      : {total_impulse:.2f} N·s')
    print(f'  Impulse (from ∫F dt): {calc_impulse:.2f} N·s')
    print(f'  Max Thrust (scalar): {max_thrust_sc:.2f} N')
    print(f'  Max Thrust (curve) : {float(thrust_curve.max()):.2f} N')
    print(f'  Peak Pressure      : {peak_pres:.3f} MPa')
    print(f'  Curve TV (thrust)  : {float(np.mean(np.abs(np.diff(thrust_curve)))):.2f} ↓smoother<100')
    print('=' * 58)

    if plot:
        fig, axes = plt.subplots(1, 2, figsize=(14, 5))
        fig.suptitle('Finocyl V3 — Predicted Performance', fontsize=13, fontweight='bold')

        axes[0].fill_between(time_steps, thrust_curve, alpha=0.2, color='red')
        axes[0].plot(time_steps, thrust_curve, 'r-', lw=2.5)
        axes[0].set_title(f'Thrust Curve  Max={thrust_curve.max():.0f} N')
        axes[0].set_xlabel('Time (s)'); axes[0].set_ylabel('Thrust (N)')
        axes[0].set_ylim(bottom=0); axes[0].grid(True, alpha=0.3)

        axes[1].fill_between(time_steps, pressure_curve, alpha=0.2, color='blue')
        axes[1].plot(time_steps, pressure_curve, 'b-', lw=2.5)
        axes[1].set_title(f'Pressure Curve  Max={pressure_curve.max():.2f} MPa')
        axes[1].set_xlabel('Time (s)'); axes[1].set_ylabel('Pressure (MPa)')
        axes[1].set_ylim(bottom=0); axes[1].grid(True, alpha=0.3)

        plt.tight_layout()
        plt.show()

    return {
        'thrust_curve'   : thrust_curve,
        'pressure_curve' : pressure_curve,
        'time_steps'     : time_steps,
        'burn_time'      : burn_time,
        'isp'            : isp,
        'total_impulse'  : total_impulse,
        'max_thrust'     : float(thrust_curve.max()),
        'peak_pressure'  : float(pressure_curve.max()),
    }

print('✅ predict_finocyl_v3() defined')
print('\nExample:')
print('  result = predict_finocyl_v3(')
print('      diameter=16, length=50, core_diameter=3,')
print('      num_fins=6, fin_length=1, fin_width=0.6,')
print('      throat_diameter=1.8, exit_diameter=2.7')
print('  )')